on:
  pull_request:
    branches:
      - main
      - master
      - development
  push:
    branches:
      - main
      - master
      - development
    paths:
      - .github/workflows/render-module-rmd.yaml
      - Biomass_core.Rmd
      - Biomass_core.R

name: Render module Rmd

jobs:
  render:
    if: "!contains(github.event.commits[0].message, '[skip-ci]')"
    name: Render module Rmd
    runs-on: ubuntu-20.04

    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v2

      - uses: r-lib/actions/setup-pandoc@v2

      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - name: Install additional system dependencies
        run: |
          sudo apt-get install -y \
            libcurl4-openssl-dev \
            libgdal-dev \
            libgeos-dev \
            libgit2-dev \
            libglpk-dev \
            libmagick++-dev \
            libproj-dev \
            libudunits2-dev \
            libxml2-dev \
            python3-gdal

      - name: Install remotes, knitr, rmarkdown, bookdown, git2r, openxlsx, kableExtra, pander
        run: |
          install.packages("remotes")
          remotes::install_cran("rmarkdown")
          remotes::install_cran("knitr")
          remotes::install_cran("bookdown")
          remotes::install_cran("git2r")
          remotes::install_cran("openxlsx")
          remotes::install_cran("kableExtra")
          remotes::install_cran("pander")
        shell: Rscript {0}

      - name: Install SpaDES packages
        run: |
          install.packages("SpaDES", dependencies = TRUE)
          remotes::install_github("PredictiveEcology/SpaDES.docs@development")
        shell: Rscript {0}

      - name: Install module package dependencies
        run: |
          pkgs <- SpaDES.core::packages(modules = "Biomass_core", paths = "..")
          Require::Require(pkgs[[1]])
        shell: Rscript {0}

      - name: Render module Rmd
        run: |
          rmarkdown::render("Biomass_core.Rmd", encoding = "UTF-8")
        shell: Rscript {0}

      - name: Commit results
        run: |
          git config user.email "actions@github.com"
          git config user.name "GitHub Actions"
          git commit Biomass_core.html -m 'Re-build Biomass_core.Rmd' || echo "No changes to commit"
          git push https://${{github.actor}}:${{secrets.GITHUB_TOKEN}}@github.com/${{github.repository}}.git HEAD:${{github.ref}} || echo "No changes to commit"
